### ISSUE TITLE
English version

### ISSUE THREAD

**Issue by BigGitWorld** [ZHENFENG13/My-Blog#107]
@ZHENFENG13 
Hi.
Thank you for this nice project.
Do you have any plan to support English version as a default language?

**Comment by ZHENFENG13** [comment]
不熟悉英文博客，暂时无计划。

**Comment by BigGitWorld** [comment]
@ZHENFENG13
Thank you for your answer.
Please use **tags and release** for next versions, so that people be able to understand major releases.
Thank you again.
