### ISSUE TITLE
一个类文件问题

### ISSUE THREAD

**Issue by XYFFFFFF** [ZHENFENG13/My-Blog#112]
在ErrorPageControlle.java文件中有下列方法，其中参数 boolean includeStackTrace 是一个boolean类型的，但是getErrorAttributes中要求的是ErrorAttributeOptions类型，请问该问题应该怎么解决呢

` protected Map<String, Object> getErrorAttributes(HttpServletRequest request, boolean includeStackTrace) {
        WebRequest webRequest = new ServletWebRequest(request);
        return this.errorAttributes.getErrorAttributes(webRequest, includeStackTrace);
    } `

**Comment by XYFFFFFF** [comment]
是版本问题，我自己更新了一个版本出错了

**Comment by ZHENFENG13** [comment]
嗯嗯。
