### ISSUE TITLE
友情链接update后再save，save会变成update

### ISSUE THREAD

**Issue by roibin** [ZHENFENG13/My-Blog#119]
友情链接修改后再新增，此时新增变为update，而不是save，貌似是主键的问题？

**Comment by ZHENFENG13** [comment]
我看下，有问题的话我改一下。

**Comment by roibin** [comment]
save插入采用自增主键，无指定id。update后的主键被save用来作为插入id，所以插入的数据覆盖了原先update的数据，而不是重新自增主键插入数据。
不懂得怎么改😂

**Comment by roibin** [comment]
老哥，那个MyBlogUtil工具类下的CleanString()具体用途是什么？看不太懂，转为html？
