### ISSUE TITLE
非 docker 环境下部署，首次打开页面非常慢

### ISSUE THREAD

**Issue by fightljd** [ZHENFENG13/My-Blog#16]
看了一下get 请求/ 耗时将近4分多钟，传输6.74kb数据，这个是正常吗？只是首次打开时出现这种情况，当界面加载正常后，再打开就很快了。代码还没来得及看，不知道首次打开时做了什么操作这么耗时。不知道大家有遇到这种情况没？

**Comment by xiaoxiugege** [comment]
我也是 非常慢，过了第一次之后就好了。看启动log 是因为家在模板所以慢
