### ISSUE TITLE
非docker环境运行启动500错误

### ISSUE THREAD

**Issue by 54dongjun** [ZHENFENG13/My-Blog#18]
启动target目录下的Jar包，在浏览器：http://localhost:8080/myblog/ 报错500，http://localhost:8080/myblog/admin 报错
Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.

Wed Jul 26 13:28:12 CST 2017
There was an unexpected error (type=Not Found, status=404).
No message available

log里面报错内容：

2017-07-26 13:27:53.647 [http-nio-8080-exec-3] ERROR com.my.blog.website.controller.GlobalExceptionHandler - find exception:e=query content by id and return is not one
query content by id and return is not one
请问这个是什么问题啊

**Comment by ZHENFENG13** [comment]
404错误啊，为什么地址里你要加"myblog"?

**Comment by 54dongjun** [comment]
直接输入 :localhost:8080 现在没问题了，但是后台 locahost:8080/admin 的登录有点问题，输入用户和密码弹出下载窗口，无法登陆。。。

**Comment by ZHENFENG13** [comment]
嗯，建议用chrome
