### ISSUE TITLE
在Linux上启动时间较长

### ISSUE THREAD

**Issue by LemonCoo1** [ZHENFENG13/My-Blog#2]
![image](https://cloud.githubusercontent.com/assets/19984894/26273892/c2882920-3d6d-11e7-931a-87a64d223fcf.png)
启动服务器100多秒
第一次请求 初始化thymeleaf 也差不多100秒,这一块应该可以优化一下

**Comment by ZHENFENG13** [comment]
这个有毒吧，哈哈哈，我没碰到过这么久的，linux是什么配置的

**Comment by LemonCoo1** [comment]
@ZHENFENG13    2核2G的不算很差吧

**Comment by ZHENFENG13** [comment]
就是个普通的web应用，不可能这么夸张吧，100秒有点儿意外啊，我也是部署在linux的
