### ISSUE TITLE
页面底部备案号

### ISSUE THREAD

**Issue by 120851380** [ZHENFENG13/My-Blog#20]
<img width="279" alt="2017-08-08 5 08 12" src="https://user-images.githubusercontent.com/12827067/29064864-f5c751c0-7c5c-11e7-8fe9-ca489ec0b1ce.png">
备案号这个地方的显示问题，直接用的镜像没法改页面。

**Comment by ZHENFENG13** [comment]
好的，我把它改成配置项吧

**Comment by ZHENFENG13** [comment]
已修复
