### ISSUE TITLE
BaseInterceptor.java中csrf_token 有验证逻辑嘛？ 

### ISSUE THREAD

**Issue by ghost** [ZHENFENG13/My-Blog#22]
`if (request.getMethod().equals("GET")) {
            String csrf_token = UUID.UU64();
            // 默认存储30分钟
            cache.hset(Types.CSRF_TOKEN.getType(), csrf_token, uri, 30 * 60);
            request.setAttribute("_csrf_token", csrf_token);
        }`

这里不是很明白！！！求大神指教！！！

**Comment by ZHENFENG13** [comment]
你全局搜索一下"_csrf_token"就行了，这里并不是登录验证。

**Comment by jounghu** [comment]
@ZHENFENG13 明白了，在评论的时候，做了refer和csrf双重校验！！学习了，用你这个项目学习springboot+themyleaf真好！我想拜你为师！！！！！

**Comment by ZHENFENG13** [comment]
@jounghu 谢谢支持！
