### ISSUE TITLE
request 与 model

### ISSUE THREAD

**Issue by lmovse** [ZHENFENG13/My-Blog#23]
发现项目里填充 view 时用的都是 `request.setAttribute`, 是个人习惯吗？

**Comment by ZHENFENG13** [comment]
嗯，顺手就写了，你有更好的方法的话，欢迎修改😁

**Comment by lmovse** [comment]
晕，嗯。我改成 model 了，方便测试，换成框架本身支持的数据绑定格式也方便解耦合 😄

**Comment by ZHENFENG13** [comment]
好的，但是没看到你fork，所以看不到你修改的代码

**Comment by lmovse** [comment]
(⊙﹏⊙)b，我直接下载压缩包了。。进行了太多的修改，页面啊，配置啊，命名啊，改成了自己比较喜欢的风格，而且用了 tkmybatis，去掉了 example 和 mapper

**Comment by ZHENFENG13** [comment]
好吧，可以的话发我一份。

**Comment by lmovse** [comment]
嗯嗯，好的。整理完发你一份。:smile:
