### ISSUE TITLE
是否可以考虑加入是否展示文章的功能

### ISSUE THREAD

**Issue by RunningDream** [ZHENFENG13/My-Blog#30]
比如有些文章是作者不想展示的，可以新增一个是否展示文章的功能，来让作者选择是否需要展示。

**Comment by ZHENFENG13** [comment]
有草稿啊

**Comment by RunningDream** [comment]
这个还是不一样吧，草稿给人的感觉是还没写完。但是是否展示，是写完了，暂时不想展示而已。

**Comment by ZHENFENG13** [comment]
你可以自己实现的，也不难，加一个状态字段的事情。
