### ISSUE TITLE
在thymeleaf模板引擎中调用主题公共函数是如何实现的？

### ISSUE THREAD

**Issue by ss2468776986** [ZHENFENG13/My-Blog#31]
<a th:href="${commons.permalink(article)}"></a>
如上会调用Commons中的permalink()函数，然而我新建一个Spring Boot+Thymeleaf项目（非作者项目）却无法实现，提示Method call: Attempted to call method test() on null context object（test()是测试的方法）；查了很多thymeleaf的教程也没有提到过这个，望解答

**Comment by ZHENFENG13** [comment]
thymeleaf 的context，即提供数据的地方，基于web的context，即WebContext相对context增加 param,session,application变量，并且自动将request atttributes添加到context variable map，可以在模板直接访问。

**Comment by ZHENFENG13** [comment]
http://www.cnblogs.com/han-1034683568/p/7527564.html
