### ISSUE TITLE
Failed to execute goal com.spotify:docker-maven-plugin:0.3.258:build (

### ISSUE THREAD

**Issue by StudyLifeTime** [ZHENFENG13/My-Blog#35]
docker docker compose 安装完成
在docker-extends 目录下 执行 ./run.sh
报一下错误：
```
Failed to execute goal com.spotify:docker-maven-plugin:0.3.258:build (default) on project my-blog: Exception caught: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:2375 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused) -> [Help 1]
```

**Comment by ZHENFENG13** [comment]
运行如下脚本即可：
```docker run -d -v /var/run/docker.sock:/var/run/docker.sock -p 2375:2375 bobrik/socat TCP4-LISTEN:2375,fork,reuseaddr UNIX-CONNECT:/var/run/docker.sock```

可以看一下这篇文章：[Docker on Mac上的Remote API 远程控制](https://github.com/ZHENFENG13/My-Blog/wiki/Docker-on-Mac%E4%B8%8A%E7%9A%84Remote-API-%E8%BF%9C%E7%A8%8B%E6%8E%A7%E5%88%B6)
