### ISSUE TITLE
老铁你不厚道啊，参考的代码地址也不贴一下吗，最起码的尊重呢？

### ISSUE THREAD

**Issue by ted-wq-x** [ZHENFENG13/My-Blog#39]

**Comment by ZHENFENG13** [comment]
老铁，你好，早前的README.md文件中是提到过参考项目的，后来做了改动，现在放在了介绍博客[开源博客My BLog](http://www.cnblogs.com/han-1034683568/p/6840493.html)文章中了，你的项目我提交过pr，但是你没接受Ｏ(≧口≦)Ｏ所以我才另外新建了一个项目，现在还能看到我的pr记录.....😁 我想试着联系过你，但是实在找不到你的联系方式(￣△￣)

**Comment by ted-wq-x** [comment]
老铁，我么有看到，因为是你自己close的，不是我，所以没有提醒

发自我的 iPhone

在 2017年10月25日，上午10:01，涵 <notifications@github.com<mailto:notifications@github.com>> 写道：


老铁，你好，早前的README.md文件中是提到过参考项目的，后来做了改动，现在放在了介绍博客开源博客My BLog<http://www.cnblogs.com/han-1034683568/p/6840493.html>文章中了，你的项目我提交过pr，但是你没接受Ｏ(≧口≦)Ｏ所以我才另外新建了一个项目，现在还能看到我的pr记录.....😁 我想试着联系过你，但是实在找不到你的联系方式(￣△￣)

**Comment by ZHENFENG13** [comment]
因为我当时在练习docker，所以就试着改了，那次pr如果你接受了，我就不会再做拓展了(￣△￣)

**Comment by ted-wq-x** [comment]
我的意思是，给个起码的最重，你改我的代码当然开心，只是我没看到你的pr！希望你以后注意下，你自己也用了apache的协议，我想这个你应该清楚

发自我的 iPhone

在 2017年10月25日，上午11:23，涵 <notifications@github.com<mailto:notifications@github.com>> 写道：


因为我当时在练习docker，所以就试着改了，那次pr如果你接受了，我就不会再做拓展了(￣△￣)

**Comment by ZHENFENG13** [comment]
嗯，你的意思我知道，不好意思啊，因为之前改了几次README.md文档，可以加一下你好友吗？qq微信都行

**Comment by ted-wq-x** [comment]
736445126

发自我的 iPhone

在 2017年10月25日，下午12:05，涵 <notifications@github.com<mailto:notifications@github.com>> 写道：


嗯，你的意思我知道，不好意思啊，因为之前改了几次README.md文档，可以加一下你好友吗？qq微信都行

**Comment by LoveMyt** [comment]
可以把你docker的心得稍微写一下嘛   docker 照着你那样发布成功了  但是没有感觉到docker的方便 或者说部署集群的时候的优势 我的意思是说怎么样能体现出docker部署项目比传统的取linux上部署项目感觉更好  或者说 一个linux下 部署多个docker，   我 可能在官网上 看的不太明白， 希望博主能给予帮助哈   可能有点小偷懒的意思了

**Comment by ted-wq-x** [comment]
老哥你能够想象，只要一行命令就能在一个新的机器上部署一个服务吗，不需要配置环境变量参数等等乱七八糟的东西，这就是docker的优点，对于集群的意义就更大了，这是给我的最直观的感受 @LoveMyt
