### ISSUE TITLE
为什么数据库选型为mysql

### ISSUE THREAD

**Issue by liangyuanpeng** [ZHENFENG13/My-Blog#4]
为什么不继续用小巧的sqlite

**Comment by liangyuanpeng** [comment]
刚好我最近刚刚搭建好原来的系统框架tale博客，我的想法也是用一段时间摸清了架构思想后自己重构，刚好今天看到你的github，简直就是我想要的

**Comment by ZHENFENG13** [comment]
习惯了呗，你也可以改成sqlite的
