### ISSUE TITLE
数据库连接池的URL配置处的mysql:3306问题？

### ISSUE THREAD

**Issue by KouLouYiMaSi** [ZHENFENG13/My-Blog#41]
这个mysql:3306我试了下，mysql是启动myblog容器的时候--link 设置的连接名
问题是这个mysql:3306在哪里被解析成ip:3306的？
另外这种配置方式是在哪个文档里看到的？
还望您赐教，不胜感激

**Comment by ted-wq-x** [comment]
[参考这个demo](https://github.com/jiwhiz/spring-boot-docker-mysql)

**Comment by KouLouYiMaSi** [comment]
怎么连接我是知道的，但不知道为什么这样写，database 的url为什么可以写成 （连接名:3306）

**Comment by ted-wq-x** [comment]
你看下，docker-compose.yml文件，有写啊，mysql端口没有暴露到宿主机，所以ip+端口没用，使用docker进行容器连接

**Comment by KouLouYiMaSi** [comment]
我并没有按照作者的教程启动docker-compose，而是把所有docker-compose相关的文件删掉了，然后手动启动mysql数据库，再启动my-blog服务，同样也是可以利用连接名连接到数据库，疑惑的地方就是为什么可以使用连接名+端口的形式，是哪部分代码负责解析这个连接名的

**Comment by ted-wq-x** [comment]
老哥，你启动时没加配置文件参数，则使用默认的，也就是application-default.properties，这里面使用的localhost

**Comment by icepoint0** [comment]
作者是个抄袭者

**Comment by ted-wq-x** [comment]
他没有写源头我有和他说，原始版本是叫tale，他的这个版本是我改的，他修改成docker部署的方式。是有这个嫌疑

发自我的 iPhone

在 2017年12月22日，下午3:49，i <notifications@github.com<mailto:notifications@github.com>> 写道：


作者是个抄袭者
