### ISSUE TITLE
博客国际化问题

### ISSUE THREAD

**Issue by namsiz** [ZHENFENG13/My-Blog#47]
博客系统确实很好！想知道当前支不支持中英文切换功能？或者想实现国际化功能从那边入手？

**Comment by ZHENFENG13** [comment]
暂时还没这个想法。

**Comment by ted-wq-x** [comment]
你可以和原作者联系[tale](https://github.com/otale/tale)

**Comment by troublrMan** [comment]
我想国际化不如，设计成可以用户注册的论坛模式比较更好。当然如果爬虫一些知名网站的blog首页展示就更好的了。






在 2017-11-15 16:36:31，"ALX" <notifications@github.com> 写道：


博客系统确实很好！想知道当前支不支持中英文切换功能？或者想实现国际化功能从那边入手？
