### ISSUE TITLE
部署在tomcat，打开文章详情报错

### ISSUE THREAD

**Issue by yihuxz** [ZHENFENG13/My-Blog#49]
部署在tomcat，打开文章详情报错。看了下是因为url路径不对，部署在tomcat后，页面跳转应该是/myblog/article/{id}。但是打开文章详情是的url还是/article/{id}。查了下在properties文件中，加入server.context-path可以解决。但是打开后台，登录时还是报错，也是url没有待/myblog。对spring不是很熟，查了很久没找到原因。所以想请教下，该怎样去修改的？

**Comment by ted-wq-x** [comment]
修改Tomcat的网站根目录或是使用nginx代理，代码有可能有点问题使用了绝对路径，可以修改下

**Comment by yihuxz** [comment]
嗯。谢谢。已经改为部署在tomcat根目录了。
