### ISSUE TITLE
修复两个bug

### ISSUE THREAD

**Issue by zhisheng17** [ZHENFENG13/My-Blog#5]
1、博客首页最好加个通过 index 也可以访问 ，解决方法在  controller 包下的 indexcontroller 中的首页加上 index，如下 `@GetMapping(value = {"/", "index"})` 
2、博客管理后台注销用户没用，原因是因为 ` AuthController .java` 下的 logout 方法的`response.sendRedirect(Commons.site_url());`     ，这个 `site_url()` 方法最后只返回空， 所以不会注销用户，我的解决方法就是在  `Commons.java`   中加个方法，如下：

```
/**
     * 在管理员页面退出登录返回到登录界面
     * @return
     */
    public static String site_login() {
        return "admin/login";
    }
```

然后 logout 方法 中使用 `response.sendRedirect(Commons.site_login());`   即可实现点击注销用户后跳转到 登录状态。

**Comment by ZHENFENG13** [comment]
好的，今天会做一下修改
