### ISSUE TITLE
抄袭人家的也说一下好吗

### ISSUE THREAD

**Issue by icepoint0** [ZHENFENG13/My-Blog#52]
loser

**Comment by retuenepz** [comment]
ice gay

**Comment by SShnoodles** [comment]
[https://github.com/otale/tale](url)

**Comment by ZHENFENG13** [comment]
这个项目是基于tale的docker版本，在开源时已经做过说明：《[Docker+SpringBoot+Mybatis+thymeleaf的Java博客系统开源啦](http://www.cnblogs.com/han-1034683568/p/6840493.html)》

**Comment by SShnoodles** [comment]
建议更新到readme，并添加连接。
