### ISSUE TITLE
设置contextPath的问题

### ISSUE THREAD

**Issue by WindBruce** [ZHENFENG13/My-Blog#53]
## 应部署需要设置contextPath，但设置了就无法正常使用了
当在application-default.properties中设置contextPath时（server.context-path=/xv），项目url路由失效。

**Comment by ted-wq-x** [comment]
哪个路由失败，以及你是使用哪种方式启动的，说清楚

**Comment by WindBruce** [comment]
application-default.properties中设置 server.context-path=/blog ,便于一个tomcat一个端口部署多个项目，相当于全局url前都加入一个/blog前缀，如管理员登录地址变成：http://localhost:8080/blog/admin,其他任何页面均是一样，这么配置首页加载就已不能正常显示，应该是没有考虑到这种情况。

**Comment by ted-wq-x** [comment]
你在控制台看下是不是有什么资源报错，如果有就取代码中html上看看，很好修改有可能是页面的资源路径写的有问题

**Comment by WindBruce** [comment]
ok
