### ISSUE TITLE
操作到打包部署项目那一步就报错了，没有生成war包

### ISSUE THREAD

**Issue by hq1148365306** [ZHENFENG13/My-Blog#56]
[root@izwz98ej2lk1sl3ik96bn3z ~]# mvn clean package  -Dmaven.test.skip=true
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.137 s
[INFO] Finished at: 2018-01-31T11:24:53+08:00
[INFO] Final Memory: 4M/27M
[INFO] ------------------------------------------------------------------------
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/root). Please verify you invoked Maven from the correct directory. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException

**Comment by tonychancode** [comment]
[root@izwz98ej2lk1sl3ik96bn3z ~]# mvn clean package -Dmaven.test.skip=true
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/root). Please verify you invoked Maven from the correct directory. -> [Help 1]

error msg says it all~
seems u're using command line tool under /root directory?
u need to go into the project directory, eg.: /root/My-Blog, that's where there's pom.xml and working directory for maven.

**Comment by ZHENFENG13** [comment]
只是想打包的话直接用mvn命令行就好了
