### ISSUE TITLE
这个项目是基于tale的springboot和docker版本

### ISSUE THREAD

**Issue by huclengyue** [ZHENFENG13/My-Blog#59]
https://github.com/otale/tale

**Comment by ZHENFENG13** [comment]
这个项目是基于tale的springboot和docker版本，在开源时已经做过说明：《[Docker+SpringBoot+Mybatis+thymeleaf的Java博客系统开源啦](http://www.cnblogs.com/han-1034683568/p/6840493.html)》

**Comment by huclengyue** [comment]
额 没有其他意思 纯属好奇。。。因为我py写的后端也是tale的模板。。。纯属好奇。。
