### ISSUE TITLE
360极速浏览器中管理员登录界面出现问题

### ISSUE THREAD

**Issue by zhisheng17** [ZHENFENG13/My-Blog#6]
使用 360极速浏览器在管理员登录界面出现问题如下图

![sp20170614_171514](https://user-images.githubusercontent.com/10086212/27125015-7f6fafca-5125-11e7-9db7-61d0f0b797d3.png)

**Comment by zhisheng17** [comment]
但是我使用 火狐浏览器 却不会出现这个问题，这是什么原因呢？

**Comment by ZHENFENG13** [comment]
这个就不确定了，我用的是chrome和safari，没出现过这种情况
