### ISSUE TITLE
Idea运行没问题,打包成jar在linux上运行报空指针异常,启动失败 .日志文件已经上传

### ISSUE THREAD

**Issue by tranceyu** [ZHENFENG13/My-Blog#62]
[nohup.txt](https://github.com/ZHENFENG13/My-Blog/files/2238752/nohup.txt)

**Comment by liyufeng123-live** [comment]
> 搞定了，在pom里面把mysql的版本换成5.1.44就行了。。



> 我是这样配的 <img alt="snipaste_2018-08-11_22-01-44" width="756" src="https://user-images.githubusercontent.com/38209858/43992991-6ee880c8-9db9-11e8-9ed8-2ee3bd7347a0.png">



> 我的是这样配的 <img alt="snipaste_2018-08-11_22-01-44" width="756" src="https://user-images.githubusercontent.com/38209858/43992991-6ee880c8-9db9-11e8-9ed8-2ee3bd7347a0.png">

**Comment by liyufeng123-live** [comment]
不要把ip暴露了，老哥
