### ISSUE TITLE
Couldn't connect to Docker daemon at http+docker://localhost - is it running?

### ISSUE THREAD

**Issue by sunshanpeng** [ZHENFENG13/My-Blog#67]
sh -x run.sh时报错
+cd docker-extension
+docker-compose stop
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.

这个要怎么解决啊？

**Comment by ZHENFENG13** [comment]
docker装了吗？装了的话docker服务启动了么？
