### ISSUE TITLE
安装你的操作用docker在服务器上部署mysql连接好像有问题，遇见过吗

### ISSUE THREAD

**Issue by forzzh** [ZHENFENG13/My-Blog#73]
mysql_1    | 2018-05-07 23:02:56.881 [Druid-ConnectionPool-Create-319689067] ERROR com.alibaba.druid.pool.DruidDataSource - create connection error, url: jdbc:mysql://mysql:3306/tale?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true, errorCode 0, state 08001
mysql_1    | com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
mysql_1    | 	at sun.reflect.GeneratedConstructorAccessor43.newInstance(Unknown Source) ~[?:?]
mysql_1    | 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_111]
mysql_1    | 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_111]
mysql_1    | 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.40.jar!/:5.1.40]
mysql_1    | 	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-java-5.1.40.jar!/:5.1.40]
mysql_1    | 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:918) ~[mysql-connector-java-5.1.40.jar!/:5.1.40]
mysql_1    | 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:897) ~[mysql-connector-java-5.1.40.jar!/:5.1.40]
mysql_1    | 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:886) ~[mysql-connector-java-5.1.40.jar!/:5.1.40]
mysql_1    | 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:860) ~[mysql-connector-java-5.1.40.jar!/:5.1.40]
mysql_1    | 	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2163) ~[mysql-connector-java-5.1.40.jar!/:5.1.40]
mysql_1    | 	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2088) ~[mysql-connector-java-5.1.40.jar!/:5.1.40]
mysql_1    | 	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:806) ~[mysql-connector-java-5.1.40.jar!/:5.1.40]
mysql_1    | 	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47) ~[mysql-connector-java-5.1.40.jar!/:5.1.40]
mysql_1    | 	at sun.reflect.GeneratedConstructorAccessor41.newInstance(Unknown Source) ~[?:?]
mysql_1    | 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_111]
mysql_1    | 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_111]
mysql_1    | 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.40.jar!/:5.1.40]
mysql_1    | 	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:410) ~[mysql-connector-java-5.1.40.jar!/:5.1.40]
mysql_1    | 	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:328) ~[mysql-connector-java-5.1.40.jar!/:5.1.40]
mysql_1    | 	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1408) ~[druid-1.0.18.jar!/:1.0.18]
mysql_1    | 	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1464) ~[druid-1.0.18.jar!/:1.0.18]
mysql_1    | 	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1969) [druid-1.0.18.jar!/:1.0.18]
mysql_1    | Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
mysql_1    | 
mysql_1    | The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
mysql_1    | 	at sun.reflect.GeneratedConstructorAccessor39.newInstance(Unknown Source) ~[?:?]
mysql_1    | 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_111]
mysql_1    | 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_111]
mysql_1    | 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.40.jar!/:5.1.40]
mysql_1    | 	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:989) ~[mysql-connector-java-5.1.40.jar!/:5.1.40]
mysql_1    | 	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:341) ~[mysql-connector-java-5.1.40.jar!/:5.1.40]
mysql_1    | 	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2251) ~[mysql-connector-java-5.1.40.jar!/:5.1.40]
mysql_1    | 	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2104) ~[mysql-connector-java-5.1.40.jar!/:5.1.40]
mysql_1    | 	... 12 more
mysql_1    | Caused by: java.net.UnknownHostException: mysql
mysql_1    | 	at java.net.InetAddress.getAllByName0(InetAddress.java:1280) ~[?:1.8.0_111]
mysql_1    | 	at java.net.InetAddress.getAllByName(InetAddress.java:1192) ~[?:1.8.0_111]
mysql_1    | 	at java.net.InetAddress.getAllByName(InetAddress.java:1126) ~[?:1.8.0_111]
mysql_1    | 	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:188) ~[mysql-connector-java-5.1.40.jar!/:5.1.40]
mysql_1    | 	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:300) ~[mysql-connector-java-5.1.40.jar!/:5.1.40]
mysql_1    | 	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2251) ~[mysql-connector-java-5.1.40.jar!/:5.1.40]
mysql_1    | 	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2104) ~[mysql-connector-java-5.1.40.jar!/:5.1.40]
mysql_1    | 	... 12 more

**Comment by ZHENFENG13** [comment]
用docker-compose了吗

**Comment by forzzh** [comment]
用了docker-compose
#此脚本于2017年8月9日再次更新

mysql:
  image: registry.cn-hangzhou.aliyuncs.com/13/myblog:mysql

 #测试时使用
  ports:
   - 13306:3306

my-blog:
  image: registry.cn-hangzhou.aliyuncs.com/13/myblog:blog
  ports:
   - 28080:8080
  links:
   - mysql

然后使用docker ps查看是否启动
CONTAINER ID        IMAGE                                              COMMAND             CREATED              STATUS              PORTS                     NAMES
2d6a4599b65a        registry.cn-hangzhou.aliyuncs.com/13/myblog:blog   "sh /startup.sh"    About a minute ago   Up About a minute   0.0.0.0:28080->8080/tcp   docker_my-blog_1
80ad4172d35c        registry.cn-hangzhou.aliyuncs.com/13/myblog        "sh /startup.sh"    About a minute ago   Up About a minute   0.0.0.0:13306->3306/tcp   docker_mysql_1

**Comment by ZHENFENG13** [comment]
我重新走了一遍流程，启动compose脚本-->拉取镜像-->构建-->访问，发现一切正常，步骤截图如下：

### 启动
![](https://raw.githubusercontent.com/ZHENFENG13/resource/master/images/2018-05-08/start.png)

### 日志
![](https://raw.githubusercontent.com/ZHENFENG13/resource/master/images/2018-05-08/logs.png)

### 访问
![](https://raw.githubusercontent.com/ZHENFENG13/resource/master/images/2018-05-08/28080.png)

应该是其他方面的原因，你连接一下mysql能否连接成功，或者看一下compose日志是否有其他异常。

**Comment by forzzh** [comment]
mysql不能连接成功，同样的操作步骤，我在本机macOS上可以成功运行，在centos的云服务器上就失败了 。。。第一次用docker，我先熟悉熟悉，过2天再重新操作下找找服务器上失败的原因==

**Comment by ZHENFENG13** [comment]
好的
