### ISSUE TITLE
怎么进后台登录页面

### ISSUE THREAD

**Issue by qumj123** [ZHENFENG13/My-Blog#77]
怎么进后台登录页面

**Comment by qumj123** [comment]
谢谢


------------------ 原始邮件 ------------------
发件人: "十三"<notifications@github.com>;
发送时间: 2019年8月2日(星期五) 下午2:04
收件人: "ZHENFENG13/My-Blog"<My-Blog@noreply.github.com>;
抄送: "相濡以沫"<305502220@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [ZHENFENG13/My-Blog] 怎么进后台登录页面 (#77)




/admin

**Comment by PYQ0423** [comment]
![image](https://user-images.githubusercontent.com/17025457/68576900-fbe08180-04a9-11ea-80aa-c2b9a6712fe5.png)
服务器没有响应。

**Comment by wen0668** [comment]
请问支不支持多用户管理和新用户注册的功能？

**Comment by wen0668** [comment]
自行部署了blog 到本地服务器，但访问后台时，验证码显示不出来。提示接口报错：/common/kaptcha  500 Internal Server Error

**Comment by ZHENFENG13** [comment]
> 请问支不支持多用户管理和新用户注册的功能？

你可以自行开发新功能哈
