### ISSUE TITLE
Tomcat 下启动保错，麻烦帮我看下这是什么问题呢

### ISSUE THREAD

**Issue by wmdkanhai** [ZHENFENG13/My-Blog#79]
error creating bean with name 'authController': Failed to introspect bean class [com.my.blog.website.controller.admin.AuthController] for lookup method metadata: could not find class that it depends on; nested exception is java.lang.NoClassDefFoundError: org/apache/catalina/servlet4preview/http/HttpServletRequest

**Comment by ZHENFENG13** [comment]
包导错了吧，换成```javax.servlet.http.HttpServletRequest```

**Comment by wmdkanhai** [comment]
不是，我再idea下运行没有问题，然后想打成 war 包，然后在 Tomcat 下启动的时候保错了

**Comment by wmdkanhai** [comment]
还真是导包的问题，十分感谢

**Comment by wmdkanhai** [comment]
在 AuthController.java 文件中，导入了import org.apache.catalina.servlet4preview.http.HttpServletRequest;

麻烦您再源码中修改下吧。
