### ISSUE TITLE
为什么后面加上/admin还是不能进入管理台呀？

### ISSUE THREAD

**Issue by troublrMan** [ZHENFENG13/My-Blog#8]
为什么后面加上/admin还是不能进入管理台呀？
![image](https://user-images.githubusercontent.com/12270005/27476967-4b52025a-583d-11e7-96fd-c176124791ac.png)

**Comment by ZHENFENG13** [comment]
这个是代码报错了，你看最后一行报错，我下班了没带电脑，你先自己试着解决一下

**Comment by ZHENFENG13** [comment]
/admin/login
