### ISSUE TITLE
编辑器显示有问题

### ISSUE THREAD

**Issue by viviov** [ZHENFENG13/My-Blog#81]
![image](https://user-images.githubusercontent.com/12570557/62345541-5cfcce80-b525-11e9-974f-ab60f30a284a.png)
这是写好的，并且预览正常
![image](https://user-images.githubusercontent.com/12570557/62345577-7867d980-b525-11e9-8816-5391fdec7fc5.png)
访问显示就变成这样了

**Comment by ZHENFENG13** [comment]
这是格式乱掉了，代码块格式前面加个空格试试

**Comment by viviov** [comment]
> 这是格式乱掉了，代码块格式前面加个空格试试
不行，感觉对MarkDown编辑支持的有点问题~

**Comment by ZHENFENG13** [comment]
我试了一下，效果如下：

- **详情页**

![image](https://user-images.githubusercontent.com/10935614/62362090-d6f57d80-b54e-11e9-822c-de35ec3fb8b8.png)

- **后台**

![image](https://user-images.githubusercontent.com/10935614/62362205-1623ce80-b54f-11e9-99f7-e20c44bf5987.png)

文章地址：http://13blog.site/blog/11236

**Comment by viviov** [comment]
感谢回复，你是自己敲空格然后标序号的。你试试使用那上面编辑提供的自动标号和TAB控制间距，多用一点上面的功能，显示出来格式都是乱的
