### ISSUE TITLE
底部备案号的一个建议

### ISSUE THREAD

**Issue by wycweb** [ZHENFENG13/My-Blog#84]
建议将底部备案号添加跳转链接到http://www.beian.gov.cn/

看下这个的第十三条 和 二十五条规定：http://www.gov.cn/gongbao/content/2005/content_93018.htm
在备案编号下方按要求链接信息产业部备案管理系统网址，供公众查询核对。

**Comment by ZHENFENG13** [comment]
感觉需要的话大家自行添加吧，就不写在项目里了。
