### ISSUE TITLE
请问为何给出的管理员用户无法登陆，，，

### ISSUE THREAD

**Issue by inverai** [ZHENFENG13/My-Blog#87]
![image](https://user-images.githubusercontent.com/17284308/41651191-8d472356-74b2-11e8-9dcc-934bcd2d1844.png)
![image](https://user-images.githubusercontent.com/17284308/41651281-c5a9ae76-74b2-11e8-9df3-7e48ef188e4e.png)

**Comment by ZHENFENG13** [comment]
哪里无法登陆？

**Comment by inverai** [comment]
姐姐，就这个登陆界面呀。。
/admin/login 这里

**Comment by ZHENFENG13** [comment]
明天看一下，没带电脑回来

**Comment by inverai** [comment]
好的，麻烦了。

**Comment by ZHENFENG13** [comment]
默认就是admin，123456，看了数据也没问题，你看一下日志，在登陆的时候执行的sql是什么。


另外，密码生成方式你可以在项目里搜一下这个类：Pwdtest.java
```
public class Pwdtest {
    public static void main(String args[]){
        UserVo user = new UserVo();
        user.setUsername("admin");
        user.setPassword("123456");
        String encodePwd = TaleUtils.MD5encode(user.getUsername() + user.getPassword());
        System.out.println(encodePwd);
    }
}
```

**Comment by inverai** [comment]
嗯，好吧，我刚才看了下，之前是我搞错了，，不好意思，

**Comment by ZHENFENG13** [comment]
嗯，OK
