### ISSUE TITLE
添加对LaTex数学公式的支持

### ISSUE THREAD

**Issue by Mrhs121** [ZHENFENG13/My-Blog#89]
在footer.html中添加这段js，即可在浏览博客页面的时候将LaTex数学公式转换成相应的数学格式！非常漂亮！

`<script th:src="@{//cdn.mathjax.org/mathjax/latest/MathJax.js}" > </script>`

`<script type="text/x-mathjax-config">  `

`  MathJax.Hub.Config({  `

`     extensions: ["tex2jax.js"],  `

`    jax: ["input/TeX", "output/HTML-CSS"],  `

`    tex2jax: {. `

`      inlineMath: [ ['$','$'], ["\\(","\\)"] ],  `

`      displayMath: [ ['$$','$$'], ["\\[","\\]"] ],  `

`      processEscapes: true`

`    },  
`
`    "HTML-CSS": { availableFonts: ["TeX"] }  `

`  });`

`</script>`

**Comment by ZHENFENG13** [comment]
感谢提醒，issue已置顶，需要的朋友可以自行添加
