### ISSUE TITLE
请教关于页面显示乱码

### ISSUE THREAD

**Issue by megustasyzy** [ZHENFENG13/My-Blog#95]
大佬你好，想请教一下为什么我项目运行页面显示会乱码啊，数据库innodb 然后数据库编码utf8，数据库配置只改了连接用户与密码别的没动，按照网上别人说法配置加了页面响应编码为utf8并且重写了启动类也不行

**Comment by limaonet** [comment]
页面乱码是 view 乱码吗 还是 你启动的 console 乱码啊

**Comment by megustasyzy** [comment]
> 页面乱码是 view 乱码吗 还是 你启动的 console 乱码啊

页面，就是web上面显示内容乱码，我有直接在数据库中查，是正常的

**Comment by limaonet** [comment]
1.简单的话试试 换个浏览器, 
2.view 是页面 页面乱码找应用服务,咱们spring boot 内置个tomcat  如果是你用内置的话 看看是否设置了编码.外置同理

**Comment by megustasyzy** [comment]
> 页面乱码是 view 乱码吗 还是 你启动的 console 乱码啊



> 1.简单的话试试 换个浏览器,
> 2.view 是页面 页面乱码找应用服务,咱们spring boot 内置个tomcat 如果是你用内置的话 看看是否设置了编码.外置同理



> 1.简单的话试试 换个浏览器,
> 2.view 是页面 页面乱码找应用服务,咱们spring boot 内置个tomcat 如果是你用内置的话 看看是否设置了编码.外置同理

目前试过chrome和safari，都是乱码显示，我直接邮件您看图

**Comment by megustasyzy** [comment]
> > 页面乱码是 view 乱码吗 还是 你启动的 console 乱码啊
> 
> > 1.简单的话试试 换个浏览器,
> > 2.view 是页面 页面乱码找应用服务,咱们spring boot 内置个tomcat 如果是你用内置的话 看看是否设置了编码.外置同理
> 
> > 1.简单的话试试 换个浏览器,
> > 2.view 是页面 页面乱码找应用服务,咱们spring boot 内置个tomcat 如果是你用内置的话 看看是否设置了编码.外置同理
> 
> 目前试过chrome和safari，都是乱码显示，我直接邮件您看图

桥豆麻袋，我把邮件发到项目作者那儿去了😂

**Comment by limaonet** [comment]
这里直接可以把图片粘贴过来
  大家一起看看  吧!

**Comment by megustasyzy** [comment]
![image](https://user-images.githubusercontent.com/33707489/70885809-e0224b00-2014-11ea-8262-e6bf6568fd41.png)
就像这个样子，chrome也是一样的

**Comment by limaonet** [comment]
这个是 数据乱码吧 你看下 f12 调试下后台 的数据是不是乱码

**Comment by megustasyzy** [comment]
f12显示都是乱码的

**Comment by limaonet** [comment]
后台的问题 ,返回的数据格式你在idea 里面看是因为 idea 他可以设置编码格式, 但是不代表 数据是设密码格式!

**Comment by megustasyzy** [comment]
谢谢大佬，😂我再看看

**Comment by zxsz4084** [comment]
不太了解楼主的情况，是不是sql读取出来前，先执行 set names utf-8 后再执行sql返回？

**Comment by ZHENFENG13** [comment]
debug 模式看一下是 controller 层、service 层还是 dao 层乱码的，具体可以参考我之前写的这篇文章：https://www.cnblogs.com/han-1034683568/p/6517344.html

**Comment by megustasyzy** [comment]
> debug 模式看一下是 controller 层、service 层还是 dao 层乱码的，具体可以参考我之前写的这篇文章：https://www.cnblogs.com/han-1034683568/p/6517344.html
确定了是dao时候查询结果就是乱码的

**Comment by megustasyzy** [comment]
页面初始化时候就查到了全是乱码的东西但事实上，数据库查询是没问题的，hu怀疑是环境有什么问题因为启动时候打印了很多类似这样的东西
`
============================
CONDITIONS EVALUATION REPORT
============================


Positive matches:
-----------------

   CodecsAutoConfiguration matched:
      - @ConditionalOnClass found required class 'org.springframework.http.codec.CodecConfigurer' (OnClassCondition)

   CodecsAutoConfiguration.JacksonCodecConfiguration matched:
      - @ConditionalOnClass found required class 'com.fasterxml.jackson.databind.ObjectMapper' (OnClassCondition)

   CodecsAutoConfiguration.JacksonCodecConfiguration#jacksonCodecCustomizer matched:
      - @ConditionalOnBean (types: com.fasterxml.jackson.databind.ObjectMapper; SearchStrategy: all) found bean 'jacksonObjectMapper' (OnBeanCondition)

   DataSourceAutoConfiguration matched:
`
![image](https://user-images.githubusercontent.com/33707489/70892885-f33d1700-2024-11ea-95d3-ab70651df7af.png)

**Comment by megustasyzy** [comment]
启动时候控制台打印了这些内容
`
============================
CONDITIONS EVALUATION REPORT
============================


Positive matches:
-----------------

   CodecsAutoConfiguration matched:
      - @ConditionalOnClass found required class 'org.springframework.http.codec.CodecConfigurer' (OnClassCondition)

   CodecsAutoConfiguration.JacksonCodecConfiguration matched:
      - @ConditionalOnClass found required class 'com.fasterxml.jackson.databind.ObjectMapper' (OnClassCondition)

   CodecsAutoConfiguration.JacksonCodecConfiguration#jacksonCodecCustomizer matched:
      - @ConditionalOnBean (types: com.fasterxml.jackson.databind.ObjectMapper; SearchStrategy: all) found bean 'jacksonObjectMapper' (OnBeanCondition)

   DataSourceAutoConfiguration matched:
`

**Comment by megustasyzy** [comment]
![image](https://user-images.githubusercontent.com/33707489/70894369-d5bd7c80-2027-11ea-8380-04577b5309e8.png)
![image](https://user-images.githubusercontent.com/33707489/70894601-48c6f300-2028-11ea-9d97-bf169bf4e302.png)

以上是sql查询和debug内容，参数无问题，查询实体是乱码，确认数据库和表编码格式是utf8

**Comment by megustasyzy** [comment]
问题的症结在于，MySQL的“utf8”实际上不是真正的UTF-8。
“utf8”只支持每个字符最多三个字节，而真正的UTF-8是每个字符最多四个字节。
MySQL一直没有修复这个bug，他们在2010年发布了一个叫作“utf8mb4”的字符集，绕过了这个问题。
当然，他们并没有对新的字符集广而告之（可能是因为这个bug让他们觉得很尴尬），以致于现在网络上仍然在建议开发者使用“utf8”，但这些建议都是错误的。
简单概括如下：
MySQL的“utf8mb4”是真正的“UTF-8”。
MySQL的“utf8”是一种“专属的编码”，它能够编码的Unicode字符并不多。
所有在使用“utf8”的MySQL和MariaDB用户都应该改用“utf8mb4”，永远都不要再使用“utf8”。
Mac端的navicat（Windows的目前没试过）需要配置数据库连接的编码类型为utf8mb4或者自动，否则在navicat上面执行插入脚本插入的中文就是Latin类型
