### ISSUE TITLE
数据库驱动默认是8.*吗？数据库与数据库驱动一直不一致。。。

### ISSUE THREAD

**Issue by zhyyyyyyy** [ZHENFENG13/My-Blog#98]

**Comment by zhyyyyyyy** [comment]
我的数据库版本是5.5.22，我将驱动jar包改为5.1.47，报at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.47.jar:5.1.47]的错

**Comment by WaylanPunch** [comment]
不用改，我的数据库是5.7的，用8.0的connector也没问题
